-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.articulo
(
    precio numeric(38, 2) NOT NULL,
    stock integer NOT NULL,
    id_articulo bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_categoria bigint,
    id_productor bigint NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    imagen_url character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT articulo_pkey PRIMARY KEY (id_articulo)
);

CREATE TABLE IF NOT EXISTS public.carrito
(
    finalizado boolean,
    gastos_envio numeric(38, 2),
    impuestos numeric(38, 2),
    subtotal numeric(38, 2),
    total numeric(38, 2),
    fecha_creacion timestamp(6) with time zone,
    id_carrito bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cliente bigint,
    CONSTRAINT carrito_pkey PRIMARY KEY (id_carrito)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion text COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    imagen_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    fecha_registro timestamp(6) without time zone,
    id_cliente bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_usuario bigint,
    direccion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT cliente_id_usuario_key UNIQUE (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.detalle_carrito
(
    cantidad integer,
    cantidad_articulos integer,
    cantidad_lotes integer,
    precio_unitario numeric(38, 2),
    total_linea numeric(38, 2),
    id_articulo bigint,
    id_carrito bigint NOT NULL,
    id_detalle_carrito bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT detalle_carrito_pkey PRIMARY KEY (id_detalle_carrito)
);

CREATE TABLE IF NOT EXISTS public.detalle_ovp
(
    cantidad integer,
    precio_unitario numeric(38, 2),
    id_articulo bigint,
    id_detalle_ovp bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_ovp bigint,
    CONSTRAINT detalle_ovp_pkey PRIMARY KEY (id_detalle_ovp)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    cantidad integer,
    precio_unitario numeric(38, 2),
    total_linea numeric(38, 2),
    id_articulo bigint,
    id_detalle_pedido bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_pedido bigint NOT NULL,
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id_detalle_pedido)
);

CREATE TABLE IF NOT EXISTS public.orden_venta_productor
(
    fecha_creacion timestamp(6) with time zone,
    id_ovp bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_pedido bigint,
    id_pedido_cliente bigint,
    id_productor bigint,
    estado character varying(255) COLLATE pg_catalog."default",
    numero_orden character varying(255) COLLATE pg_catalog."default",
    observaciones character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT orden_venta_productor_pkey PRIMARY KEY (id_ovp),
    CONSTRAINT orden_venta_productor_numero_orden_key UNIQUE (numero_orden)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    gastos_envio numeric(38, 2),
    iva numeric(38, 2),
    subtotal numeric(38, 2),
    total numeric(38, 2),
    fecha_pedido timestamp(6) with time zone,
    id_cliente bigint NOT NULL,
    id_pedido bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado_pedido character varying(255) COLLATE pg_catalog."default",
    id_transaccion character varying(255) COLLATE pg_catalog."default",
    metodo_pago character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.productor
(
    fecha_registro timestamp(6) without time zone,
    id_productor bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_usuario bigint,
    direccion character varying(255) COLLATE pg_catalog."default",
    imagen_url character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT productor_pkey PRIMARY KEY (id_productor),
    CONSTRAINT productor_id_usuario_key UNIQUE (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(255) COLLATE pg_catalog."default",
    tipo_usuario character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.articulo
    ADD CONSTRAINT fk7n3o8lpr7d7uy4pxv4cueloal FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.articulo
    ADD CONSTRAINT fkn43ijnxlo3gfc2wxg2ejwfu1f FOREIGN KEY (id_productor)
    REFERENCES public.productor (id_productor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.carrito
    ADD CONSTRAINT fkry3lix3gwxchdayl4i5sh7y4f FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT fketx0tojxf5yevxcyt6qb526x5 FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS cliente_id_usuario_key
    ON public.cliente(id_usuario);


ALTER TABLE IF EXISTS public.detalle_carrito
    ADD CONSTRAINT fkksf5v77lctre0m1yu9vea3qbu FOREIGN KEY (id_articulo)
    REFERENCES public.articulo (id_articulo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_carrito
    ADD CONSTRAINT fkry3h7i75daoi59gena2xl3d6n FOREIGN KEY (id_carrito)
    REFERENCES public.carrito (id_carrito) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_ovp
    ADD CONSTRAINT fk375bkifcs68493j37mn6l1m16 FOREIGN KEY (id_ovp)
    REFERENCES public.orden_venta_productor (id_ovp) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_ovp
    ADD CONSTRAINT fkhyo3qb8nftltg4nhx468qq5jq FOREIGN KEY (id_articulo)
    REFERENCES public.articulo (id_articulo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT fk7n9hdifr08joboojejveby1vr FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT fkmmgw1ju1dfci3scs40te1y4bi FOREIGN KEY (id_articulo)
    REFERENCES public.articulo (id_articulo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orden_venta_productor
    ADD CONSTRAINT fk70fn3774kscppeha4sqjvkh0k FOREIGN KEY (id_productor)
    REFERENCES public.productor (id_productor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orden_venta_productor
    ADD CONSTRAINT fkkx4d4maeosekw09oj7l56e603 FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orden_venta_productor
    ADD CONSTRAINT fklys77f2ao5gr1hxha9ep4ryqd FOREIGN KEY (id_pedido_cliente)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fk9y4jnyp1hxqa386cnly0ay9uw FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productor
    ADD CONSTRAINT fkqdg6jaja3xs285m7w6puc1qa4 FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS productor_id_usuario_key
    ON public.productor(id_usuario);

END;